### PR TITLE
Null safety support

### LINKED ISSUE #12: Null-safety support
It's just about the right time to start migrating packages to support null-safety.

[Announcing Dart null safety beta](https://medium.com/dartlang/announcing-dart-null-safety-beta-87610fee6730)

Is someone already working on this or is it open for contributions? :)

### PR DESCRIPTION
**Pull request by Albert221**
https://medium.com/dartlang/announcing-dart-null-safety-beta-87610fee6730

- I bumped the Dart SDK constraint to 2.12 prerelease which supports null-safety.
- I formatted some of the lines using dartfmt and replaced double quotes with single quotes.
- I fixed error I got in example pubspec when running `flutter pub get`.

I also made some types in methods non-nullable. Please someone revise this if this will work for the library :) I thought that the device strings/bools/etc cannot be nullable, but logs can.

Closes #12.

### CODE REVIEW

**Comment by jgimenez** [comment]
Thanks for your contribution @Albert221 . I see however that none of the parameters can be null. Is it maybe only a matter of upgrading the SDK dependency?

**Comment by Albert221** [comment]
I'm not sure if I understand your concern correctly. Dart 1.12 introduces null-safety, meaning that all types are now non nullable by default and adding the question mark makes them nullable. I'm happy to discuss more on this PR :)

**Comment by jgimenez** [comment]
Sorry if I wasn't clear: what I mean is that only a few of those parameters that you made nullable by adding the ? are actually nullable. Only the `init` method accepts null parameters. The rest of methods are expecting a non-null parameter.

**Comment by Albert221** [comment]
Ah, okay! Proceeding to fix it then

**Review by jgimenez — APPROVED** [review]

**Comment by jgimenez** [comment]
Thanks!

**Pull request merged**
